### ISSUE TITLE
ios build faild

### ISSUE THREAD

**Issue by sallenhandong** [sishuguojixuefu/react-native-template-sishu#1]
when i build
Showing Recent Messages
:-1: /Users/mac/Desktop/rn/react-native-typescript-template-master/ios/Pods/Pods/Target Support Files/Pods-AwesomeProject/Pods-AwesomeProject.debug.xcconfig: unable to open file (in target "AwesomeProject" in project "AwesomeProject") (in target 'AwesomeProject')

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/65475103-e2ab5380-deb0-11e9-91e7-5f021329045d.png)

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/65475970-f906de80-deb3-11e9-8dca-2b22b4ee75ad.png)

**Comment by sallenhandong** [comment]
thank you,my react-native version is 0.60
